declare
   l_workspace_id      number;
 begin
     l_workspace_id := apex_util.find_security_group_id (p_workspace => 'KSCOPE21');
     apex_util.set_security_group_id (p_security_group_id => l_workspace_id);
 end;
/


-------------------------
-- Recreate the datamodel
-------------------------

drop table auto_sales;
drop table auto_products;
drop table auto_customers;
drop table auto_channels;
drop table auto_promotions;
  
-- create tables
create table auto_products (
    id                             number generated by default on null as identity 
                                   constraint auto_products_id_pk primary key,
    name                           varchar2(50 char),
    description                    varchar2(4000 char),
    sku                            varchar2(30 char),
    unit                           number,
    unit_price                     number,
    status_short                  varchar2(1),
    status_long                   varchar2(10)
)
;

create table auto_customers (
    id                             number generated by default on null as identity 
                                   constraint auto_customers_id_pk primary key,
    first_name                     varchar2(255 char),
    last_name                      varchar2(255 char),
    email                          varchar2(255 char),
    city                           varchar2(255 char),
    country                        varchar2(50 char),
    gender                         varchar2(6 char) constraint auto_customers_gender_cc
                                   check (gender in ('MALE','FEMALE')),
    date_of_birth                  date,
    phone                          varchar2(30 char),
    postal_code                    varchar2(30 char)
)
;

create table auto_channels (
    id                             number generated by default on null as identity 
                                   constraint auto_channels_id_pk primary key,
    name                           varchar2(6 char) constraint auto_channels_name_cc
                                   check (name in ('DIRECT','ONLINE','PHONE'))
)
;

create table auto_promotions (
    id                             number generated by default on null as identity 
                                   constraint auto_promotions_id_pk primary key,
    name                           varchar2(255 char),
    code                           varchar2(10 char),
    date_begin                     date,
    date_end                       date,
    discount_percentage            number
)
;

create table auto_sales (
    id                             number generated by default on null as identity 
                                   constraint auto_sales_id_pk primary key,
    product_id                     number
                                   constraint auto_sales_product_id_fk
                                   references auto_products on delete cascade,
    customer_id                    number
                                   constraint auto_sales_customer_id_fk
                                   references auto_customers on delete cascade,
    promotion_id                   number
                                   constraint auto_sales_promotion_id_fk
                                   references auto_promotions on delete cascade,
    channel_id                     number
                                   constraint auto_sales_channel_id_fk
                                   references auto_channels on delete cascade,
    date_of_sale                   date,
    quantity                       number,
    unit_price                     number
)
;

-- table index
create index auto_sales_i1 on auto_sales (channel_id);
create index auto_sales_i2 on auto_sales (customer_id);
create index auto_sales_i3 on auto_sales (product_id);
create index auto_sales_i4 on auto_sales (promotion_id);


-- create views
create or replace view auto_sales_v as 
select 
    products.id                                        product_id,
    products.name                                      product_name,
    products.description                               description,
    products.sku                                       sku,
    products.unit                                      unit,
    products.unit_price                                product_unit_price,
    customers.id                                       customer_id,
    customers.first_name                               first_name,
    customers.last_name                                last_name,
    customers.email                                    email,
    customers.city                                     city,
    customers.country                                  country,
    customers.gender                                   gender,
    customers.date_of_birth                            date_of_birth,
    customers.phone                                    phone,
    customers.postal_code                              postal_code,
    channels.id                                        channel_id,
    channels.name                                      channel_name,
    promotions.id                                      promotion_id,
    promotions.name                                    promotion_name,
    promotions.code                                    code,
    promotions.date_begin                              date_begin,
    promotions.date_end                                date_end,
    promotions.discount_percentage                     discount_percentage,
    sales.id                                           sale_id,
    sales.date_of_sale                                 date_of_sale,
    sales.quantity                                     quantity,
    sales.unit_price                                   sale_unit_price
from 
    auto_products products,
    auto_customers customers,
    auto_channels channels,
    auto_promotions promotions,
    auto_sales sales
where
    sales.product_id(+) = products.id and
    sales.customer_id(+) = customers.id and
    sales.promotion_id(+) = promotions.id and
    sales.channel_id(+) = channels.id
/

-- load data
 
-- Generated by Quick SQL Wednesday June 09, 2021  06:08:20
 
/*
products 
   name vc50
   description
   sku vc30
   unit num
   unit price num

customers 
   first name
   last name
   email
   city
   country vc50
   gender  vc30 /check Male, Female
   date of birth
   phone vc30
   postal code vc30

channels 
   name /check direct, online, phone

promotions 
   name
   code vc10
   date begin
   date end
   discount percentage  num

sales 
   product id
   customer id
   promotion id
   channel id
   date of sale
   quantity num
   unit price num

view sales_v products customers channels promotions sales

# settings = { prefix: "AUTO", PK: "IDENTITY", semantics: "CHAR", language: "EN", APEX: true }
*/


----------------------------------------
-- Create a blueprint from the datamodel
----------------------------------------

-- Drop the blueprint (if exists)
begin
  apex_dg_data_gen.remove_blueprint(p_name  => 'Product Sales');
exception
  when no_data_found then
    null;
end;
/

declare
  l_blueprint_id number;
begin
  apex_dg_data_gen.add_blueprint_from_tables(
                    p_name           => 'Product Sales',
                    p_tables         =>  apex_t_varchar2('auto_products:5','auto_customers:5', 'auto_channels:3', 'auto_promotions:3', 'auto_sales:10'),       
                    p_description    => 'A blueprint to generate product sales data',
                    p_blueprint_id   => l_blueprint_id
                    );                  
end;
/    

----------------------------------
-- Generate data for the blueprint
----------------------------------

declare
    l_output    blob;
begin
    l_output :=
    apex_dg_output.generate_data
        (p_blueprint          => 'Product Sales',
         p_format             => 'FAST INSERT INTO'
        );
        
    --htp.p(utl_raw.cast_to_varchar2(l_output));
end;
/

-------------------------------------------
-- Check the result (verify number of rows)
-------------------------------------------

select * from auto_products;
select * from auto_customers;
select * from auto_channels;
select * from auto_promotions;
select * from auto_sales;

select count(*) from auto_products;
select count(*) from auto_customers;
select count(*) from auto_channels;
select count(*) from auto_promotions;
select count(*) from auto_sales;